### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by mrtysn** [renatorib/react-sizes#16]
Does this project work when using SSR? I have seen #15 but it has not been merged yet.

It would be great to know if you are going to be supporting SSR soon. Thanks

**Comment by renatorib** [comment]
Yeah, it support SSR. But you need to check. Since we can't have the window sizes in the server, it will be `false`

```js
const mapSizesToProps = ({ width }) => ({
  showSidebar: width && width < 500,
})
```

`showSidebar` will be false on server.

If you want to discover the user's device, you can manually check the user-agent (from server request headers). 

I don't have expertise, but I guess it's something like this:
```js
// somewhere on server request (express, etc.)
global.navigator = {
  userAgent: req.headers['user-agent']
}

// on your component
const checkIfUserAgentIsMobile = () => { ... }
const mapSizesToProps = ({ width }) => ({
  isMobile: width ? width < 500 : checkIfUserAgentIsMobile(navigator.userAgent)
})
```

**Comment by renatorib** [comment]
@mrtysn see https://github.com/renatorib/react-sizes/pull/23
I've added SizesProvider that can help with SSR
