### ISSUE TITLE
The size is not specified on initial render

### ISSUE THREAD

**Issue by AugustinLF** [renatorib/react-sizes#7]
I really like using react-sizes, the API is really nice to use, but it seems to me that on the initial render, the components don't have access to the size returned by the `mapSizesToProps`. Since you initialise the event listeners in the `componentDidMount`, it's logical. However, couldn't you do this initialization in the `componentWillMount` (while checking of course that we're not server-side) ? This would avoid a flash of styles on first render, and would also let me correctly use the prop-types (here, if I have a a `mobile: PropTypes.bool.isRequired`, I'll get a warning).

If you're interested, I'd be happy to submit a PR :)

**Comment by renatorib** [comment]
Nice! You have a good point, and we can think in a solution for this. But, let me list some useful things:

1. At `componentWillMount` we may not have access to DOM yet, in most of cases. I think it's a bad approach, and I want to _avoid_ this. Even with properly checks.

2. Flashing of content is suck, so I've using this 'tricky-way' in my own projects/job: returning null when dom is not available.

```jsx
const MyComponent = ({ isMobile, canUseDOM }) => {
  if (!canUseDOM) return null;

  return (
    <div>{isMobile ? 'Is Mobile' : 'Is Not Mobile'}</div>
  );
};

const mapSizesToProps = ({ width }) => ({
  canUseDOM: !!width, // width and height returns false when it's not available
  isMobile: width < 480,
});

export Sizes(mapSizesToProps)(MyComponent);
```

Even knowing this is not a elegant way, I think it can do a good workaround to avoiding flashing of contents.

3. About prop-types, I think it's not a big problem, since you can do a checks that guarantee it will be boolean.

```js
const mapSizesToProps = ({ width }) => ({
  canUseDOM: !!width,
  isMobile:  !!width && width < 480, // will be false in server/first render. ever a boolean
});
```

Thanks for your issue, it's a really good discussion, and more people can leave their opinions too!

**Comment by renatorib** [comment]
@AugustinLF do you have some more points of view to share? I'll love to hear about your opinion! :D

**Comment by elisechant** [comment]
react-sizes-redux ? and hook in to uiReducer

**Comment by AugustinLF** [comment]
@renatorib Sorry for the delay, was a bit busy^^ And I need to admit, I don't have any strong conviction on the matter. I'm curious as of why you're saying:
> I think it's a bad approach, and I want to avoid this. Even with properly checks.

That's something I used to do in a previous project (with a form of homemade react-sizes), and I didn't have any problems with that.

Because I agree that in a lot of situations, simply not rendering as long as the DOM is not available, but let's consider a simple example: I have a side menu, that is initially expanded on desktop, and closed on tablet. Should I just then render the menu after the rest of the app? Right now, the menu closes after the didMount on tablet (which is not great, of course).

@elisechant  as-of react-sizes-redux, I'm not sure of what you mean :/ But I did have an idea with that, where the library would fall back on the useragent when the DOM is not available (which would let us get a correct render most of the time), useragent that you can easily save in your store. But the implementation would of course be much trickier.

**Comment by seekshiva** [comment]
@AugustinLF I've built a solution for this that works something like this:

```jsx
<LayoutParent>
  <div>
     {rest of my app goes here...}
  </div>
</LayoutParent>
```

`LayoutParent` is sort of a higher level component that needs to be added at the root of the project, just like you do `Provider` of react-redux or `Router` of react-router.

`LayoutParent` will initially render an empty div and calculate width, height of the page on `componentDidMount`... and once the layout information is stored on screen, it will render its children. This way, an empty div is rendered just once in the entire lifecycle of the app and not every single time you call `sizes()`.

`LayoutParent` detects the dimensions of the page once during the lifecycle of the app and passes the information down to its children via React's context api - so that components that need to listen to dimensions can just do so by listening to the context. I've provided a HOC `layoutSubscribe()` which will listen to the size info in context and pass it down to my component.

Once `LayoutParent` renders, it will automatically subscribe to window.resize event, so when the page gets resized, the change is propagated to all children.

This sort of how page dimension propagation looks like:

![responsive](https://cloud.githubusercontent.com/assets/484349/25773258/72f85d9c-3298-11e7-8fcd-fe85429d9465.gif)

**Comment by seekshiva** [comment]
You can see a working demo of the above at https://inkmonk.com

**Comment by AugustinLF** [comment]
@seekshiva the problem I have with this solution, is that you cannot start rendering part of your app earlier, and cannot use SSR, right? Right now I'm building an app with nextjs. A significant part of my UI can be rendered independently from the size of the screen. But for instance, my whole menu cannot.

**Comment by seekshiva** [comment]
whenever you do

```
ReactDOM.render(<AppRoot />, document.getElementById('app'))
```
you can do 
```
ReactDOM.render(
<LayoutParent>
 <AppRoot />
</LayoutParent>,
document.getElementById('app'))
```

so if AppRoot was supposed to start rendering part of the app, it can start doing as usual. It is just that `LayoutParent` will take one event tick to render an empty div first and do measurement, and then let your app render.

about SSR, I've pondered about this quite a bit myself. It might be good to have some heuristics in your server code to try to determine if its a phone or tablet/desktop by looking at the User-Agent of the browser. And depending on that, you could perhaps inject that information into your server side rendered components? So that when someone loads from mobile, they get the mobile site in html, and same for desktop. Heuristic is, at best, a guess; but it should work for you in most cases.

**Comment by renatorib** [comment]
Fixed in [0.1.0 Release](https://github.com/renatorib/react-sizes/releases/tag/v0.1.0) - Thanks to @felthy

**Comment by yhjor** [comment]
Have a nice API but it is somehow funny that SSR is not supported: `window is not defined`

**Comment by abelkbil** [comment]
How to subscribe to the screen size. @seekshiva . I am sorry I couldn't find LayoutParent.
@seekshiva , @renatorib  Thanks
